---
title: "Problem set 1: Quadratic equation"
author: "Frances Aponte"
#format: html
format: pdf
output:
  pdf_document:
    latex_engine: xelatex
editor: visual
---

## Excercise 4
Erase the PDF report and reproduce it but this time using $a=1,b=2,c=5$.

```{r Define variables}
a=1
b=2
# c will be called k
k=5
```

```{r real solutions}
#To determine if the quadratic equation have real solutions we use the discriminant. 
real_soln<-b^2-4*a*k

if (real_soln>=0){
  soln_1<-(-b+sqrt(real_soln)/2*a)
  soln_2<-(-b-sqrt(real_soln)/2*a)
  
  cat("Real Solutions: \n")
  cat("x =", soln_1, "\n")
  cat("x =", soln_2, "\n")
} else {
  cat("No real solutions. \n")
}
```

```{r Graph, echo=FALSE}
library (ggplot2)
x<-seq(-3,3) #values for x
y<-a*x^2+b*x+k #values for y

ggplot(
  #values
  data.frame(x,y), aes(x,y)) +
  #defining the color for the quadratic function
  geom_line(color = "blue") + 
  #an horizontal line in the origin
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") + 
  #graph labeling
  labs(title = "Quadratic Equation Graph",
       x = "x",
       y = "f(x)")

```






